import type { CustomizerConfig } from '@/types'

function hexToRgb(hex: string): string {
  const clean = hex.replace('#', '')
  const r = parseInt(clean.slice(0, 2), 16)
  const g = parseInt(clean.slice(2, 4), 16)
  const b = parseInt(clean.slice(4, 6), 16)
  if (isNaN(r) || isNaN(g) || isNaN(b)) return '0,0,0'
  return `${r},${g},${b}`
}

export function generateCSS(config: CustomizerConfig, licensed = false): string {
  const {
    titleText,
    titleColor,
    headerBg,
    chatBg,
    transparentBg,
    msgBgEnabled,
    msgBgColor,
    msgBgOpacity,
    usernameColor,
    fontColor,
    fontSize,
    fontFamily,
    fontWeight,
    borderRadius,
    msgSpacing,
    paddingX,
    paddingY,
    animation,
  } = config

  const bgLine = transparentBg
    ? 'background: transparent;'
    : `background: ${chatBg};`

  const msgBgLine = msgBgEnabled
    ? `background: rgba(${hexToRgb(msgBgColor)}, ${(msgBgOpacity / 100).toFixed(2)});`
    : 'background: transparent;'

  const watermark = licensed ? '' : '\n/* NoSugar CSS Chat — nosugar.css */'

  return `/* Generated by NoSugar CSS Chat */${watermark}

#chat-overlay {
  ${bgLine}
  border-radius: ${borderRadius}px;
  overflow: hidden;
}

.chat-header {
  background: ${headerBg};
  color: ${titleColor};
  padding: 10px 14px;
}

.chat-header .title {
  content: "${titleText}";
}

.chat-body {
  ${bgLine}
  padding: 8px;
}

.chat-message {
  font-family: '${fontFamily}', sans-serif;
  font-size: ${fontSize}px;
  font-weight: ${fontWeight};
  color: ${fontColor};
  padding: ${paddingY}px ${paddingX}px;
  border-radius: ${borderRadius}px;
  margin-bottom: ${msgSpacing}px;
  ${msgBgLine}
  animation: chat${capitalize(animation)} 0.35s ease both;
}

.username {
  color: ${usernameColor};
  font-weight: 700;
  margin-right: 6px;
}

/* Animation: ${animation} */
@keyframes chat${capitalize(animation)} {
${getKeyframe(animation)}
}`
}

function capitalize(s: string) {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

function getKeyframe(animation: string): string {
  switch (animation) {
    case 'slide':
      return `  from { opacity: 0; transform: translateX(-24px); }\n  to   { opacity: 1; transform: none; }`
    case 'bounce':
      return `  0%   { opacity: 0; transform: scale(0.7); }\n  60%  { transform: scale(1.06); }\n  100% { opacity: 1; transform: scale(1); }`
    case 'fade':
      return `  from { opacity: 0; }\n  to   { opacity: 1; }`
    case 'pop':
      return `  from { opacity: 0; transform: translateY(12px) scale(0.92); }\n  to   { opacity: 1; transform: none; }`
    case 'glow':
      return `  from { opacity: 0; filter: blur(4px) brightness(2); }\n  to   { opacity: 1; filter: none; }`
    default:
      return `  from { opacity: 0; }\n  to   { opacity: 1; }`
  }
}
